### ISSUE TITLE
Is your tauri update worked

### ISSUE THREAD

**Issue by sagarpadia17** [Jackson0ne/updatertest#1]
I need your help if possible because i am getting one error in that and i am new to tauri

**Comment by Jackson0ne** [comment]
Hey @sagarpadia17,

Yup, the updater works - there's also an instructions file [here](https://raw.githubusercontent.com/Jackson0ne/updatertest/main/updater%20steps.txt).

Which part are you having an issue with in particular?

**Comment by sagarpadia17** [comment]
@Jackson0ne I got it. It was in the problem of URL of the updater.json but it was showing invalid signature so i was trying to change signature but nothing was happening. In URL I was not taking the raw part of URL thats why it was showing error btw Thanks for the reply:)

**Comment by Jackson0ne** [comment]
Cool, no worries - glad you got it sorted!
